create table public.players (
	id bigint generated by default as identity primary key,
	name text,
	bga_username text,
	bga_id bigint,
	national_team_membership_current boolean not null default false,
	national_team_membership_former boolean not null default false,
	max_bga_elo integer,
	max_bga_elo_last_periods integer[],
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now(),
	constraint players_bga_fields_consistent_check check (
		(bga_username is null and bga_id is null and max_bga_elo is null and max_bga_elo_last_periods is null)
		or (bga_username is not null and bga_id is not null)
	),
	constraint players_max_bga_elo_check check (max_bga_elo is null or max_bga_elo >= 0)
);

create unique index players_bga_username_lower_key
	on public.players (lower(bga_username))
	where bga_username is not null;

create unique index players_bga_id_key
	on public.players (bga_id)
	where bga_id is not null;

create table public.profiles (
	user_id uuid primary key references auth.users (id) on delete cascade,
	player_id bigint unique references public.players (id) on delete set null,
	phone_number text,
	bio text,
	profile_picture_path text,
	created_at timestamptz not null default now(),
	updated_at timestamptz not null default now()
);

create table public.national_championship (
	year smallint not null,
	position integer not null,
	name text not null,
	points integer not null,
	score_difference integer not null,
	primary key (year, position, name),
	constraint national_championship_year_check check (year between 1900 and 2100),
	constraint national_championship_position_check check (position > 0),
	constraint national_championship_points_check check (points >= 0)
);

create table public.online_championship (
	year smallint not null,
	position integer not null,
	bga_username text not null,
	primary key (year, position, bga_username),
	constraint online_championship_year_check check (year between 1900 and 2100),
	constraint online_championship_position_check check (position > 0)
);

create table public.tournament_results (
	id bigint generated by default as identity primary key,
	tournament_name text not null,
	year smallint not null,
	player_id bigint not null references public.players (id) on delete restrict,
	rank text not null,
	coeff_points numeric(8, 2),
	unique (tournament_name, year, player_id),
	constraint tournament_results_year_check check (year between 1900 and 2100),
	constraint tournament_results_rank_check check (
		rank ~ '^[0-9]+$' or rank in ('Q', 'R32', 'R24', 'R16', 'QF', 'SF')
	),
	constraint tournament_results_coeff_points_check check (coeff_points is null or coeff_points >= 0)
);

create table public.team_participations (
	team_contest_name text not null,
	year smallint not null,
	player_id bigint not null references public.players (id) on delete restrict,
	primary key (team_contest_name, year, player_id),
	constraint team_participations_year_check check (year between 1900 and 2100)
);

create index tournament_results_player_id_idx
	on public.tournament_results (player_id);

create index team_participations_player_id_idx
	on public.team_participations (player_id);

create index tournament_results_tournament_year_idx
	on public.tournament_results (tournament_name, year);

create index team_participations_contest_year_idx
	on public.team_participations (team_contest_name, year);

alter table public.players enable row level security;
alter table public.profiles enable row level security;
alter table public.national_championship enable row level security;
alter table public.online_championship enable row level security;
alter table public.tournament_results enable row level security;
alter table public.team_participations enable row level security;

create policy "Public can read players"
	on public.players for select
	to anon, authenticated
	using (true);


create policy "Users can update their own profile"
	on public.profiles for update
	to authenticated
	using ((select auth.uid()) = user_id)
	with check ((select auth.uid()) = user_id);

create policy "Public can read national championship results"
	on public.national_championship for select
	to anon, authenticated
	using (true);

create policy "Public can read online championship results"
	on public.online_championship for select
	to anon, authenticated
	using (true);

create policy "Public can read tournament results"
	on public.tournament_results for select
	to anon, authenticated
	using (true);

create policy "Public can read team participations"
	on public.team_participations for select
	to anon, authenticated
	using (true);

revoke all on public.players from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.national_championship from anon, authenticated;
revoke all on public.online_championship from anon, authenticated;
revoke all on public.tournament_results from anon, authenticated;
revoke all on public.team_participations from anon, authenticated;

grant select on public.players to anon, authenticated;
grant select on public.profiles to authenticated;
grant update (phone_number, bio, profile_picture_path)
	on public.profiles to authenticated;
grant select on public.national_championship to anon, authenticated;
grant select on public.online_championship to anon, authenticated;
grant select on public.tournament_results to anon, authenticated;
grant select on public.team_participations to anon, authenticated;
