create schema if not exists private;

revoke all on schema private from public;
grant usage on schema private to anon, authenticated;

create table public.permission_catalog (
	code text primary key,
	description text not null
);

insert into public.permission_catalog (code, description)
values
	('admin', 'Manage all application data and permissions'),
	('news.edit', 'Create, edit, and delete owned news')
on conflict (code) do nothing;

create table public.user_permissions (
	user_id uuid not null references auth.users (id) on delete cascade,
	permission_code text not null references public.permission_catalog (code) on delete restrict,
	granted_at timestamptz not null default now(),
	granted_by uuid not null references auth.users (id) on delete restrict,
	primary key (user_id, permission_code)
);

create or replace function private.has_permission(required_permission text)
returns boolean
language sql
stable
security definer
set search_path = private, pg_catalog
as $$
	select exists (
		select 1
		from public.user_permissions
		where user_id = (select auth.uid())
		and permission_code = required_permission
	);
$$;

revoke execute on function private.has_permission(text) from public;
grant execute on function private.has_permission(text) to authenticated;

create table public.news (
	id bigint generated by default as identity primary key,
	author_id uuid not null default auth.uid() references auth.users (id) on delete restrict,
	created_at timestamptz not null default now(),
	hide_at timestamptz,
	title_cs text,
	title_en text,
	content_cs text,
	content_en text,
	image text,
	constraint news_czech_consistency_check check ((title_cs is null) = (content_cs is null)),
	constraint news_english_consistency_check check ((title_en is null) = (content_en is null))
);

create index news_publication_idx on public.news (created_at desc)
	where hide_at is null;

create or replace view public.profile_directory
with (security_invoker = false)
as
	select player_id, bio, profile_picture_path
	from public.profiles;

alter table public.permission_catalog enable row level security;
alter table public.user_permissions enable row level security;
alter table public.news enable row level security;

drop policy if exists "Users can update their own profile" on public.profiles;

create policy "Authenticated users can read permission catalog"
	on public.permission_catalog for select
	to authenticated
	using (true);

create policy "Admins can read user permissions"
	on public.user_permissions for select
	to authenticated
	using ((select private.has_permission('admin')));

create policy "Admins can grant user permissions"
	on public.user_permissions for insert
	to authenticated
	with check (
		(select private.has_permission('admin'))
		and granted_by = (select auth.uid())
	);

create policy "Admins can update user permissions"
	on public.user_permissions for update
	to authenticated
	using ((select private.has_permission('admin')))
	with check (
		(select private.has_permission('admin'))
		and granted_by = (select auth.uid())
	);

create policy "Admins can revoke user permissions"
	on public.user_permissions for delete
	to authenticated
	using ((select private.has_permission('admin')));

create policy "Users can read their own profile"
	on public.profiles for select
	to authenticated
	using ((select auth.uid()) = user_id);

create policy "Users can update their own profile"
	on public.profiles for update
	to authenticated
	using ((select auth.uid()) = user_id)
	with check ((select auth.uid()) = user_id);

create policy "Public can read visible news"
	on public.news for select
	to anon, authenticated
	using (hide_at is null or hide_at > now());

create policy "News editors can read their own news"
	on public.news for select
	to authenticated
	using (
		author_id = (select auth.uid())
		and (select private.has_permission('news.edit'))
	);

create policy "News editors can create their own news"
	on public.news for insert
	to authenticated
	with check (
		author_id = (select auth.uid())
		and (select private.has_permission('news.edit'))
	);

create policy "News editors can update their own news"
	on public.news for update
	to authenticated
	using (
		author_id = (select auth.uid())
		and (select private.has_permission('news.edit'))
	)
	with check (
		author_id = (select auth.uid())
		and (select private.has_permission('news.edit'))
	);

create policy "News editors can delete their own news"
	on public.news for delete
	to authenticated
	using (
		author_id = (select auth.uid())
		and (select private.has_permission('news.edit'))
	);

create policy "Admins can manage profiles"
	on public.profiles for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage players"
	on public.players for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage national championship results"
	on public.national_championship for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage online championship results"
	on public.online_championship for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage tournament results"
	on public.tournament_results for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage team participations"
	on public.team_participations for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create policy "Admins can manage news"
	on public.news for all
	to authenticated
	using ((select private.has_permission('admin')))
	with check ((select private.has_permission('admin')));

create or replace function private.protect_profile_fields()
returns trigger
language plpgsql
set search_path = private, pg_catalog
as $$
begin
	if not (select private.has_permission('admin'))
	and (
		new.user_id is distinct from old.user_id
		or new.player_id is distinct from old.player_id
		or new.created_at is distinct from old.created_at
	) then
		raise exception 'Only admins can change protected profile fields';
	end if;

	new.updated_at := now();
	return new;
end;
$$;

revoke execute on function private.protect_profile_fields() from public;
grant execute on function private.protect_profile_fields() to authenticated;

create trigger profiles_protect_fields
	before update on public.profiles
	for each row execute procedure private.protect_profile_fields();

create or replace function private.protect_news_fields()
returns trigger
language plpgsql
set search_path = private, pg_catalog
as $$
begin
	if not (select private.has_permission('admin'))
	and (
		new.author_id is distinct from old.author_id
		or new.created_at is distinct from old.created_at
	) then
		raise exception 'Only admins can change protected news fields';
	end if;

	return new;
end;
$$;

revoke execute on function private.protect_news_fields() from public;
grant execute on function private.protect_news_fields() to authenticated;

create trigger news_protect_fields
	before update on public.news
	for each row execute procedure private.protect_news_fields();

revoke all on public.permission_catalog from anon, authenticated;
revoke all on public.user_permissions from anon, authenticated;
revoke all on public.news from anon, authenticated;
revoke all on public.profiles from anon, authenticated;
revoke all on public.profile_directory from anon, authenticated;

grant select on public.permission_catalog to authenticated;
grant select, insert, update, delete on public.user_permissions to authenticated;
grant select, insert, update, delete on public.news to authenticated;
grant select on public.news to anon;
grant select, insert, update, delete on public.profiles to authenticated;
grant select on public.profile_directory to anon, authenticated;
grant insert, update, delete on public.players to authenticated;
grant insert, update, delete on public.national_championship to authenticated;
grant insert, update, delete on public.online_championship to authenticated;
grant insert, update, delete on public.tournament_results to authenticated;
grant insert, update, delete on public.team_participations to authenticated;

grant usage, select on sequence
	public.players_id_seq,
	public.tournament_results_id_seq,
	public.news_id_seq
	to authenticated;
